source "https://rubygems.org"

gem "portfolyou-jekyll-theme",  path: "../"

group :jekyll_plugins do
    gem "jekyll-default-layout"
    gem "jekyll-gist"
    gem "jekyll-github-metadata"
    gem "jekyll-include-cache"
    gem "jekyll-paginate"
    gem "jemoji"
end
