source "https://rubygems.org"

gem "portfolyou-jekyll-theme",  path: "../"
gem "wdm", ">= 0.1.0" if Gem.win_platform?

group :jekyll_plugins do
    gem "jekyll-default-layout"
    gem "jekyll-gist"
    gem "jekyll-github-metadata"
    gem "jekyll-include-cache"
    gem "jekyll-paginate"
    gem "jemoji"
end
